openapi: 3.0.0
info:
  title: MCP Agent Backend API
  description: API for the MCP Agent Backend that provides AI-powered task management
  version: 1.0.0

paths:
  /api/{user_id}/chat:
    post:
      summary: Send a message to the AI assistant
      description: Processes user message through AI agent and returns response
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The user's message to the AI assistant
                  example: "Add a task to buy groceries"
                conversation_id:
                  type: string
                  description: Optional conversation ID to continue existing conversation
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174000"
              required:
                - message
      responses:
        '200':
          description: Successful response from AI assistant
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                    format: uuid
                    description: The ID of the conversation
                    example: "123e4567-e89b-12d3-a456-426614174000"
                  response:
                    type: string
                    description: The AI assistant's response
                    example: "I've created a task 'buy groceries' for you."
        '400':
          description: Bad request due to invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Invalid user_id format"
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Conversation not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Internal server error occurred"

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the task
          example: 1
        title:
          type: string
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          description: Detailed task description
          example: "Get milk, bread, and eggs"
        completed:
          type: boolean
          description: Whether the task is completed
          example: false
        priority:
          type: string
          enum: [low, medium, high, urgent]
          description: Task priority level
          example: "medium"
        user_id:
          type: integer
          description: ID of the user who owns the task
          example: 1
        created_at:
          type: string
          format: date-time
          description: When the task was created
          example: "2023-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: When the task was last updated
          example: "2023-01-01T00:00:00Z"

    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the message
          example: "123e4567-e89b-12d3-a456-426614174000"
        conversation_id:
          type: string
          format: uuid
          description: ID of the conversation this message belongs to
          example: "123e4567-e89b-12d3-a456-426614174000"
        role:
          type: string
          enum: [user, assistant, tool]
          description: Role of the message sender
          example: "user"
        content:
          type: string
          description: The actual message content
          example: "Add a task to buy groceries"
        tool_calls:
          type: string
          description: JSON string representation of tool calls made
          example: '{"name": "add_task", "arguments": {"title": "buy groceries"}}'
        created_at:
          type: string
          format: date-time
          description: When the message was created
          example: "2023-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: When the message was last updated
          example: "2023-01-01T00:00:00Z"

    Conversation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the conversation
          example: "123e4567-e89b-12d3-a456-426614174000"
        user_id:
          type: string
          description: ID of the user who owns the conversation
          example: "1"
        created_at:
          type: string
          format: date-time
          description: When the conversation was created
          example: "2023-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: When the conversation was last updated
          example: "2023-01-01T00:00:00Z"